// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_QK5NQYsAx5SWZJ-3qQW8BCfnVnR9eTg',
    appId: '1:645678969867:web:2046f79f7051569e1d030e',
    messagingSenderId: '645678969867',
    projectId: 'develop-15e0b',
    authDomain: 'develop-15e0b.firebaseapp.com',
    storageBucket: 'develop-15e0b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGnHkHV_JyEgzLT40Sa19folfyHqoxemQ',
    appId: '1:645678969867:android:b69d30d38190ea781d030e',
    messagingSenderId: '645678969867',
    projectId: 'develop-15e0b',
    storageBucket: 'develop-15e0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK8KWlcvuPUrUbDOp2S1fkRss5TjGJQXU',
    appId: '1:645678969867:ios:2e4ff42e3b34fb131d030e',
    messagingSenderId: '645678969867',
    projectId: 'develop-15e0b',
    storageBucket: 'develop-15e0b.appspot.com',
    iosBundleId: 'com.example.crudFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK8KWlcvuPUrUbDOp2S1fkRss5TjGJQXU',
    appId: '1:645678969867:ios:17d0866a891111fe1d030e',
    messagingSenderId: '645678969867',
    projectId: 'develop-15e0b',
    storageBucket: 'develop-15e0b.appspot.com',
    iosBundleId: 'com.example.crudFlutter.RunnerTests',
  );
}
